name: 'Tests for trainee-test-1'
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: installing node modules
        run: |
          sudo npm install
      - name: function testing
        run: |
          sudo npm run test
